### ISSUE TITLE
checkstyle fails on clean checkout

### ISSUE THREAD

**Issue by DALDEI** [documents4j/documents4j#31] opened 2016-06-17 21:06 UTC
git clone ..
mvn package

-- Fixing this is simple enough (but gives git the shudders during git status)
Will log separate issue for test failures after fixing the lf issue

git version 2.5.3

sh-4.3$ mvn -v
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T16:58:10-04:00)
Maven home: C:\Java\apache-maven\apache-maven-3.2.3
Java version: 1.8.0_40, vendor: Oracle Corporation
Java home: E:\Java\jdk1.8.0_40\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

```

[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building documents4j-api 1.0.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-checkstyle-plugin:2.12.1:check (validate) @ documents4j-api ---
[INFO] Starting audit...
C:\Users\DLEE\git.repo\documents4j\documents4j-api\src\main\java\com\documents4j\api\DocumentType.java:0: File does not
end with a newline.
C:\Users\DLEE\git.repo\documents4j\documents4j-api\src\main\java\com\documents4j\api\IConversionJob.java:0: File does no
t end with a newline.
C:\Users\DLEE\git.repo\documents4j\documents4j-api\src\main\java\com\documents4j\api\IConversionJobWithPriorityUnspecifi
ed.java:0: File does not end with a newline.
C:\Users\DLEE\git.repo\documents4j\documents4j-api\src\main\java\com\documents4j\api\IConversionJobWithSourceSpecified.j
ava:0: File does not end with a newline.
C:\Users\DLEE\git.repo\documents4j\documents4j-api\src\main\java\com\documents4j\api\IConversionJobWithSourceUnspecified
.java:0: File does not end with a newline.
C:\Users\DLEE\git.repo\documents4j\documents4j-api\src\main\java\com\documents4j\api\IConversionJobWithTargetUnspecified
.java:0: File does not end with a newline.
C:\Users\DLEE\git.repo\documents4j\documents4j-api\src\main\java\com\documents4j\api\IConverter.java:0: File does not en
d with a newline.
C:\Users\DLEE\git.repo\documents4j\documents4j-api\src\main\java\com\documents4j\api\IFileConsumer.java:0: File does not
 end with a newline.
C:\Users\DLEE\git.repo\documents4j\documents4j-api\src\main\java\com\documents4j\api\IFileSource.java:0: File does not e
nd with a newline.
C:\Users\DLEE\git.repo\documents4j\documents4j-api\src\main\java\com\documents4j\api\IInputStreamConsumer.java:0: File d
oes not end with a newline.
C:\Users\DLEE\git.repo\documents4j\documents4j-api\src\main\java\com\documents4j\api\IInputStreamSource.java:0: File doe
s not end with a newline.
C:\Users\DLEE\git.repo\documents4j\documents4j-api\src\main\java\com\documents4j\throwables\ConversionFormatException.ja
va:0: File does not end with a newline.
C:\Users\DLEE\git.repo\documents4j\documents4j-api\src\main\java\com\documents4j\throwables\ConversionInputException.jav
a:0: File does not end with a newline.
C:\Users\DLEE\git.repo\documents4j\documents4j-api\src\main\java\com\documents4j\throwables\ConverterAccessException.jav
a:0: File does not end with a newline.
C:\Users\DLEE\git.repo\documents4j\documents4j-api\src\main\java\com\documents4j\throwables\ConverterException.java:0: F
ile does not end with a newline.
C:\Users\DLEE\git.repo\documents4j\documents4j-api\src\main\java\com\documents4j\throwables\FileSystemInteractionExcepti
on.java:0: File does not end with a newline.
Audit done.
```

[INFO] ------------------------------------------------------------------------

**Comment by raphw** [comment] 2016-06-17 21:15
I will have a look next week. There are a few things I need to do anyways.

**Comment by raphw** [comment] 2016-06-22 13:41
Can you retry? I cannot reproduce this error but I updated the checkstyle version. I wonder if this has something to do with your Maven version.

**Comment by raphw** [comment] 2016-07-13 11:03
I am closing this, please reopen if this still is an issue.

**Closed by raphw** 2016-07-13 11:03 UTC
Labels: bug
