### ISSUE TITLE
Conversion failed for an unknown reason

### ISSUE THREAD

**Issue by Soliax** [documents4j/documents4j#30] opened 2016-04-22 12:52 UTC
Code :
`File wordFile = new File("Results/test.xlsx")
                    , target = new File("Results/ReportMSWord.pdf");
 IConverter test = LocalConverter.make();
 test.convert(wordFile).as(DocumentType.MS_EXCEL)
                                 .to(target).as(DocumentType.PDF)
                                 .prioritizeWith(1000) // optional
                                 .execute();
 test.shutDown();`

Error :

`avr. 22, 2016 2:48:18 PM com.documents4j.conversion.msoffice.MicrosoftExcelBridge startUp
INFO: From-Microsoft-Excel-Converter was started successfully
avr. 22, 2016 2:48:18 PM com.documents4j.conversion.msoffice.MicrosoftWordBridge startUp
INFO: From-Microsoft-Word-Converter was started successfully
avr. 22, 2016 2:48:18 PM com.documents4j.job.LocalConverter <init>
INFO: The documents4j local converter has started successfully
avr. 22, 2016 2:48:18 PM com.documents4j.conversion.msoffice.AbstractMicrosoftOfficeBridge doStartConversion
INFO: Requested conversion from Results\test.xlsx (application/vnd.com.documents4j.any-msexcel) to Results\ReportMSWord.pdf (application/pdf)
Exception in thread "main" com.documents4j.throwables.ConverterException: Conversion failed for an unknown reason
    at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:90)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)`

**Comment by Soliax** [comment] 2016-04-22 12:53
![image](https://cloud.githubusercontent.com/assets/18615230/14741944/ea060cec-0899-11e6-8081-ae71d52da6cc.png)

Error in the VB script

**Comment by raphw** [comment] 2016-04-22 12:56
That would mean that you specified an incorrect conversion format. The `MicrosoftExcelFormat` does however not contain any non-numeric value. Can you retry with specifying the format as `DocumentType.XLSX` instead of `DocumentType.MS_EXCEL`?

**Comment by Soliax** [comment] 2016-04-22 12:57
Done. Isn't working. Same error.

**Comment by raphw** [comment] 2016-04-22 12:59
Does this only happen for `DocumentType.PDF` as a target format or for any format?

**Comment by Soliax** [comment] 2016-04-22 13:00
Juste try with 
input : DocumentType.XLSX
output : DocumentType.CSV
Same error

**Comment by raphw** [comment] 2016-04-22 13:02
But the MS-Word converter works for you? What Windows and .NET versions are you running? The complaint is that it cannot convert the numeric argument what seems impossible. Try to run the build, if this fails, too, then there is something wrong with your VBS installation, I am afraid.

**Comment by Soliax** [comment] 2016-04-22 13:10
But the MS-Word converter works for you? 
**I don't understand this question, sorry**
What Windows and .NET versions are you running? 
**Windows 7 Enteprise 64 bit.
.NET framework instal : V2.0, V3.0, V3.5, v4.0.
The run of the build fail too.**
I'm on an enterprise computer. Cannot launch powersheel script for example. Maybe it's the issue ? Will try to make a short vb script to see if it execute or not.

**Comment by Soliax** [comment] 2016-04-22 13:15
Seem i can execute this vbs script :
`dim iRule
dim instructables

iRule="instructables"

instructables=msgbox("hello " & iRule)`

**Comment by raphw** [comment] 2016-04-22 13:16
The question means: can you convert a MS Word file with the documents4j API? That one triggers a different script so I was wondering if the error is script specific or general.

Maybe write a small script that takes an argument and converts it to an int (`CInt`). The thing that I find strange is that it is the first instruction that fails. You can also try to run the script that is contained in the project directly from the command line.

**Comment by Soliax** [comment] 2016-04-22 13:27
Can you convert a MS Word file with the documents4j API?
**No, same error**
Will make the script with an argument than converts it to an int, and also try to run yours.

**Comment by Soliax** [comment] 2016-04-22 13:35
My VBS :
`
dim value
value="0" // Same crash as yours if i set it to "A"
instructables=msgbox("hello : " & CInt(value))`

**Cannot find the location of your script. **

**Comment by raphw** [comment] 2016-04-22 14:03
I have a suspicion that the command that is sent to the command line is not correct. Does your folder in which the application is started or that contains your file contain any spaces or special characters? Maybe the escaping is off?

**Comment by Soliax** [comment] 2016-04-22 14:04
Path : C:\Users\EANTLAL\git\SDE-Parser\SDE Parser V 1.0

**Comment by raphw** [comment] 2016-04-22 14:06
I asume that that is the problem. Try to run documents4j from a location without spaces such as `SDE_Parser_V_1_0` and tell me if that helps. I will try to fix the escaping in this case once I find the time.

**Comment by Soliax** [comment] 2016-04-22 14:16
I will try that. I cannot for the moment, because data from the directory are uploaded to a sharepoint as i'm speaking. When i can do it, i will give on ETA on the issue if it's solve or not. 
Thanks for you quick response and you help.
Have a nice day,

Anton L.

**Comment by Soliax** [comment] 2016-04-22 14:39
You're right, it's the space in the folder name. Have successfully run your api without espace.

**Comment by raphw** [comment] 2016-04-22 19:12
I'll try to fix that. It sounds trivial but spaces are kind of though to deal with in Windows

**Comment by goehlian** [comment] 2016-10-21 06:31
Hi everyone,

is there any news available on the preceding issue? A workaround or a statement about the development progress? Any information would be helpful. Thanks a lot.

Anne G.

**Comment by raphw** [comment] 2016-10-21 22:57
You can work around this by placing documents4j in a folder without spaces. I will fix this at some point, but yet I did not find the time and lack a Windows work machine. Feel free to submit a PR if this feature is urgent.

**Comment by raphw** [comment] 2016-12-23 17:45
Fixed on master, will be a part on 1.0.3.

**Closed by raphw** 2016-12-23 17:45 UTC
Labels: bug

**Comment by Soliax** [comment] 2016-12-24 11:32
Thank you. :)

**Comment by raphw** [comment] 2018-10-15 16:52
Is there a log in the server? Any bytes added by a proxy or something?

**Comment by raphw** [comment] 2018-10-16 13:01
Yes, you can check the command line options to produce a server log which could help uncover this problem. Also have a look at the documentation for this.

**Comment by realslimshady-stan** [comment] 2018-10-16 14:43
Thank you, can you provide link for documentation please

**Comment by raphw** [comment] 2018-10-16 14:48
documents4j.com

**Comment by jatinborsaniya** [comment] 2019-02-19 07:16
Hello  sir,
Is working on android? i need to convert doc or docx to pdf.
When I am trying the error like this.

I/System.out: start
W/System.err: java.util.concurrent.ExecutionException: Could not complete conversion
W/System.err:     at com.documents4j.job.FailedConversionFuture.get(FailedConversionFuture.java:35)
W/System.err:     at com.documents4j.job.FailedConversionFuture.get(FailedConversionFuture.java:10)
W/System.err:     at com.documents4j.job.AbstractFutureWrappingPriorityFuture.get(AbstractFutureWrappingPriorityFuture.java:205)
W/System.err:     at com.documents4j.job.AbstractFutureWrappingPriorityFuture.get(AbstractFutureWrappingPriorityFuture.java:10)
W/System.err:     at stylishtextnew.itin.com.doctopdf.MainActivity.onCreate(MainActivity.java:75)
W/System.err:     at android.app.Activity.performCreate(Activity.java:7023)
W/System.err:     at android.app.Activity.performCreate(Activity.java:7014)
W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2734)
W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2859)
W/System.err:     at android.app.ActivityThread.-wrap11(Unknown Source:0)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1592)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err:     at android.os.Looper.loop(Looper.java:164)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6518)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
W/System.err: Caused by: com.documents4j.throwables.ConversionInputException: No converter for conversion of application/vnd.openxmlformats-officedocument.wordprocessingml.document to application/pdf available
W/System.err:     at com.documents4j.conversion.ConverterRegistry.lookup(ConverterRegistry.java:65)
W/System.err:     at com.documents4j.conversion.DefaultConversionManager.startConversion(DefaultConversionManager.java:30)
W/System.err:     at com.documents4j.job.LocalFutureWrappingPriorityFuture.startConversion(LocalFutureWrappingPriorityFuture.java:50)
W/System.err:     at com.documents4j.job.LocalFutureWrappingPriorityFuture.startConversion(LocalFutureWrappingPriorityFuture.java:11)
W/System.err:     at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:70)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
D/CONVERTPRO: ERROR Could not complete conversion

===============================

 implementation group: 'com.documents4j', name: 'documents4j-local', version: '1.0.3'
    implementation group: 'com.documents4j', name: 'documents4j-transformer-msoffice-excel', version: '1.0.3'
    testImplementation group: 'ch.qos.logback', name: 'logback-classic', version: '1.1.11'
    testImplementation group: 'org.slf4j', name: 'slf4j-simple', version: '1.6.1'
    testImplementation group: 'org.slf4j', name: 'slf4j-api', version: '1.6.1'
    implementation 'org.slf4j:slf4j-nop:1.7.25'
=====================

 File base=new File(Environment.getExternalStorageDirectory().toString()+"/abc");

        File in=new File(Environment.getExternalStorageDirectory().toString()+"/example.docx");
        File out=new File(Environment.getExternalStorageDirectory().toString()+"/ex.pdf");

        base.mkdir();
        IConverter converter = LocalConverter.builder().baseFolder(base)
                .workerPool(20, 25, 2, TimeUnit.SECONDS).processTimeout(5, TimeUnit.SECONDS).build();
        try {
            System.out.println("start");

            Future<Boolean> conversion = converter
                    .convert(in).as(DocumentType.DOCX)
                    .to(out).as(DocumentType.PDF)
                    .schedule();

            System.out.println("end: " + conversion.get());
           
        } catch (InterruptedException | ExecutionException e) {

            e.printStackTrace();
           

        } finally {
            converter.shutDown();
        }

**Comment by raphw** [comment] 2019-02-19 11:55
No, you would need to connect to a remote converter.

Am Di., 19. Feb. 2019 um 08:16 Uhr schrieb jatinborsaniya <
notifications@github.com>:

**Comment by raoiitkgp** [comment] 2019-06-04 16:13
com.documents4j.throwables.ConverterException: Conversion failed for an unknown reason
    at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:90)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)]

i am getting this issue when converting from Docx to Pdf .. any idea on this issue.

it is working some times ... not the code issue i feel .. any conditions on environment

**Comment by raphw** [comment] 2019-06-05 20:27
Is there an error message on the server? If it only happens sometimes, it is either the files that are the problem or your server is instable.

**Comment by jagriti22** [comment] 2020-05-28 11:04
Hi @raphw 
I am getting following error while converting docx into pdf.Please help me to resolve this,I would be grateful to you.
Thanks.

1107 [main] INFO com.documents4j.conversion.msoffice.MicrosoftWordBridge - From-Microsoft-Word-Converter was started successfully
1156 [main] INFO com.documents4j.job.LocalConverter - The documents4j local converter has started successfully
1268 [pool-1-thread-1] INFO com.documents4j.conversion.msoffice.MicrosoftWordBridge - Requested conversion from C:\Users\hp\Downloads\0ca6354b-a78f-4355-b99f-a0239b3770a5\temp1 (application/vnd.openxmlformats-officedocument.wordprocessingml.document) to C:\Users\hp\Downloads\0ca6354b-a78f-4355-b99f-a0239b3770a5\temp2 (application/pdf)
Exception in thread "main" java.util.concurrent.ExecutionException: Could not complete conversion
	at com.documents4j.job.FailedConversionFuture.get(FailedConversionFuture.java:35)
	at com.documents4j.job.FailedConversionFuture.get(FailedConversionFuture.java:10)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.get(AbstractFutureWrappingPriorityFuture.java:205)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.get(AbstractFutureWrappingPriorityFuture.java:10)
	at DocConv.DocxToPdf.main(DocxToPdf.java:43)
Caused by: com.documents4j.throwables.FileSystemInteractionException: Could not access target file
	at com.documents4j.util.Reaction$FileSystemInteractionExceptionBuilder.make(Reaction.java:180)
	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75)
	at com.documents4j.conversion.ExternalConverterScriptResult.resolve(ExternalConverterScriptResult.java:70)
	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:48)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:36)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:11)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by raphw** [comment] 2020-05-29 07:15
What version of documents4j are you running?

**Comment by jagriti22** [comment] 2020-07-03 10:54
Hi @raphw 
I am using following dependencies:

    compile group: 'com.documents4j', name: 'documents4j-local', version: '1.0.3'
    compile group: 'com.documents4j', name: 'documents4j-transformer-msoffice-word', version: '1.0.3'

**Comment by jagriti22** [comment] 2020-07-03 11:15
Hi @raphw 
I tried using with this dependencies,    
compile group: 'com.documents4j', name: 'documents4j-local', version: '1.1.3'
compile group: 'com.documents4j', name: 'documents4j-transformer-msoffice-word', version: '1.1.3'
Now facing below error:

5068 [main] INFO com.documents4j.conversion.msoffice.MicrosoftWordBridge - From-Microsoft-Word-Converter was started successfully
5106 [main] INFO com.documents4j.job.LocalConverter - The documents4j local converter has started successfully
5203 [pool-1-thread-1] INFO com.documents4j.conversion.msoffice.MicrosoftWordBridge - Requested conversion from C:\Users\hp\Downloads\71326b0a-9e54-409c-892e-290e19e24d62\temp1 (application/vnd.openxmlformats-officedocument.wordprocessingml.document) to C:\Users\hp\Downloads\71326b0a-9e54-409c-892e-290e19e24d62\temp2 (application/pdf)
Exception in thread "main" java.util.concurrent.ExecutionException: Could not complete conversion
	at com.documents4j.job.FailedConversionFuture.get(FailedConversionFuture.java:35)
	at com.documents4j.job.FailedConversionFuture.get(FailedConversionFuture.java:10)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.get(AbstractFutureWrappingPriorityFuture.java:205)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.get(AbstractFutureWrappingPriorityFuture.java:10)
	at DocConv.DocxToPdf.main(DocxToPdf.java:43)
Caused by: com.documents4j.throwables.ConversionInputException: The input file seems to be corrupt
	at com.documents4j.util.Reaction$ConversionInputExceptionBuilder.make(Reaction.java:159)
	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75)
	at com.documents4j.conversion.ExternalConverterScriptResult.resolve(ExternalConverterScriptResult.java:70)
	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:48)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:36)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:11)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by raphw** [comment] 2020-07-04 10:16
Try the 1.1.2 version, too. I added a password check in 1.1.2 that does not seem to be supported by all versions of MS Word.

**Comment by jagriti22** [comment] 2020-07-05 11:17
Hi @raphw ,
I added version 1.1.2 also,still facing below error.Please help me out of this.

2421 [main] INFO com.documents4j.conversion.msoffice.MicrosoftWordBridge - From-Microsoft-Word-Converter was started successfully
2450 [main] INFO com.documents4j.job.LocalConverter - The documents4j local converter has started successfully
2558 [pool-1-thread-1] INFO com.documents4j.conversion.msoffice.MicrosoftWordBridge - Requested conversion from E:\5b08cebc-916f-4ba1-b4c3-ae17fdbf8202\temp1 (application/vnd.com.documents4j.any-msword) to E:\5b08cebc-916f-4ba1-b4c3-ae17fdbf8202\temp2 (application/pdf)
Exception in thread "main" com.documents4j.throwables.ConversionInputException: The input file seems to be corrupt
	at com.documents4j.util.Reaction$ConversionInputExceptionBuilder.make(Reaction.java:159)
	at com.documents4j.util.Reaction$ExceptionalReaction.apply(Reaction.java:75)
	at com.documents4j.conversion.ExternalConverterScriptResult.resolve(ExternalConverterScriptResult.java:70)
	at com.documents4j.conversion.ProcessFutureWrapper.evaluateExitValue(ProcessFutureWrapper.java:48)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:36)
	at com.documents4j.conversion.ProcessFutureWrapper.get(ProcessFutureWrapper.java:11)
	at com.documents4j.job.AbstractFutureWrappingPriorityFuture.run(AbstractFutureWrappingPriorityFuture.java:78)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by jagriti22** [comment] 2020-07-05 11:19
Hi @raphw , Kindly find my code below ,let me know if any change required.

package DocConv;

import com.documents4j.api.DocumentType;
import com.documents4j.api.IConverter;
//import com.documents4j.job.LocalConverter;
import com.documents4j.job.LocalConverter;

import java.io.BufferedInputStream;
/*import java.io.ByteArrayOutputStream;*/
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import org.apache.commons.io.output.ByteArrayOutputStream;


public class DocxToPdf {
	
	

	 public static void main(String[] args) throws IOException, ExecutionException, InterruptedException {
		
         ByteArrayOutputStream bo = new ByteArrayOutputStream();

         InputStream in = new BufferedInputStream(new FileInputStream("E:/SampleDocxxx.docx"));
         IConverter converter = LocalConverter.builder()
                 .baseFolder(new File("E:/"))
                 .workerPool(20, 25, 2, TimeUnit.MINUTES)
                 .processTimeout(60, TimeUnit.MINUTES)
                 .build();

         boolean conversion = converter
                 .convert(in).as(DocumentType.MS_WORD)
        		//   .convert(in).as(DocumentType.DOCX)
                 .to(bo).as(DocumentType.PDF)
             //    .prioritizeWith(1000) // optional
                 .execute();
     //    conversion.get();
         try (OutputStream outputStream = new FileOutputStream("E:/document4JDocx.pdf")) {
             bo.writeTo(outputStream);
         } catch (IOException e) {
             e.printStackTrace();
         }
         in.close();
         bo.close();
     }
	/*
	 * void init() { iConverter = LocalConverter.builder() .baseFolder(new
	 * File(doc4jtemp)) .processTimeout(5L, TimeUnit.MINUTES)
	 * .workerPool(15,30,10,TimeUnit.MINUTES) .build(); } public void doc2pdf(String
	 * docPath, String pdfPath) { File source = new File(docPath); File target = new
	 * File(pdfPath); iConverter.convert(source).as(DocumentType.MS_WORD)
	 * .to(target).as(DocumentType.PDF) .execute();
	 */

}

**Comment by raphw** [comment] 2020-07-09 21:32
Code and setup seems correct. Does it also fail if you convert it manually in Word? You should extract the VBS scripts for word and try running the conversion manually what might yield a better error message.
